// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' }
import * as $0 from './routes/_app.tsx'
import * as $1 from './routes/billing/billing.ts'
import * as $2 from './routes/history/history.ts'
import * as $3 from './routes/index.tsx'
import * as $4 from './routes/product/[id].tsx'
import * as $5 from './routes/settings/settings.ts'
import * as $$0 from './islands/ProductCard.tsx'
import * as $$1 from './islands/TelegramWrapper.tsx'

const manifest = {
  routes: {
    './routes/_app.tsx': $0,
    './routes/billing/billing.ts': $1,
    './routes/history/history.ts': $2,
    './routes/index.tsx': $3,
    './routes/product/[id].tsx': $4,
    './routes/settings/settings.ts': $5,
  },
  islands: {
    './islands/ProductCard.tsx': $$0,
    './islands/TelegramWrapper.tsx': $$1,
  },
  baseUrl: import.meta.url,
  config,
}

export default manifest
